//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Service_Categoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_Categoria.CategoriaService")]
    public interface CategoriaService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Modificar_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Modificar_categoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Categoria.Modificar_categoriaResponse Modificar_categoria(Desk.Service_Categoria.Modificar_categoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Modificar_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Modificar_categoriaResponse")]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Modificar_categoriaResponse> Modificar_categoriaAsync(Desk.Service_Categoria.Modificar_categoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Eliminar_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Eliminar_categoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Categoria.Eliminar_categoriaResponse Eliminar_categoria(Desk.Service_Categoria.Eliminar_categoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Eliminar_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Eliminar_categoriaResponse")]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Eliminar_categoriaResponse> Eliminar_categoriaAsync(Desk.Service_Categoria.Eliminar_categoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Crear_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Crear_categoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Categoria.Crear_categoriaResponse Crear_categoria(Desk.Service_Categoria.Crear_categoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Crear_categoriaRequest", ReplyAction="http://Servicios/CategoriaService/Crear_categoriaResponse")]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Crear_categoriaResponse> Crear_categoriaAsync(Desk.Service_Categoria.Crear_categoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Listado_categoriasRequest", ReplyAction="http://Servicios/CategoriaService/Listado_categoriasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Categoria.Listado_categoriasResponse Listado_categorias(Desk.Service_Categoria.Listado_categoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/CategoriaService/Listado_categoriasRequest", ReplyAction="http://Servicios/CategoriaService/Listado_categoriasResponse")]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Listado_categoriasResponse> Listado_categoriasAsync(Desk.Service_Categoria.Listado_categoriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_categoria", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_categoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string desc;
        
        public Modificar_categoriaRequest() {
        }
        
        public Modificar_categoriaRequest(int id, string desc) {
            this.id = id;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_categoriaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_categoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Modificar_categoriaResponse() {
        }
        
        public Modificar_categoriaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_categoria", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_categoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public Eliminar_categoriaRequest() {
        }
        
        public Eliminar_categoriaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_categoriaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_categoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Eliminar_categoriaResponse() {
        }
        
        public Eliminar_categoriaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_categoria", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_categoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string desc;
        
        public Crear_categoriaRequest() {
        }
        
        public Crear_categoriaRequest(int id, string desc) {
            this.id = id;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_categoriaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_categoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Crear_categoriaResponse() {
        }
        
        public Crear_categoriaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified {
            get {
                return this.idCategoriaFieldSpecified;
            }
            set {
                this.idCategoriaFieldSpecified = value;
                this.RaisePropertyChanged("idCategoriaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_categorias", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_categoriasRequest {
        
        public Listado_categoriasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_categoriasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_categoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Desk.Service_Categoria.categoria[] @return;
        
        public Listado_categoriasResponse() {
        }
        
        public Listado_categoriasResponse(Desk.Service_Categoria.categoria[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoriaServiceChannel : Desk.Service_Categoria.CategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaServiceClient : System.ServiceModel.ClientBase<Desk.Service_Categoria.CategoriaService>, Desk.Service_Categoria.CategoriaService {
        
        public CategoriaServiceClient() {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Categoria.Modificar_categoriaResponse Desk.Service_Categoria.CategoriaService.Modificar_categoria(Desk.Service_Categoria.Modificar_categoriaRequest request) {
            return base.Channel.Modificar_categoria(request);
        }
        
        public string Modificar_categoria(int id, string desc) {
            Desk.Service_Categoria.Modificar_categoriaRequest inValue = new Desk.Service_Categoria.Modificar_categoriaRequest();
            inValue.id = id;
            inValue.desc = desc;
            Desk.Service_Categoria.Modificar_categoriaResponse retVal = ((Desk.Service_Categoria.CategoriaService)(this)).Modificar_categoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Modificar_categoriaResponse> Desk.Service_Categoria.CategoriaService.Modificar_categoriaAsync(Desk.Service_Categoria.Modificar_categoriaRequest request) {
            return base.Channel.Modificar_categoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Categoria.Modificar_categoriaResponse> Modificar_categoriaAsync(int id, string desc) {
            Desk.Service_Categoria.Modificar_categoriaRequest inValue = new Desk.Service_Categoria.Modificar_categoriaRequest();
            inValue.id = id;
            inValue.desc = desc;
            return ((Desk.Service_Categoria.CategoriaService)(this)).Modificar_categoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Categoria.Eliminar_categoriaResponse Desk.Service_Categoria.CategoriaService.Eliminar_categoria(Desk.Service_Categoria.Eliminar_categoriaRequest request) {
            return base.Channel.Eliminar_categoria(request);
        }
        
        public string Eliminar_categoria(int id) {
            Desk.Service_Categoria.Eliminar_categoriaRequest inValue = new Desk.Service_Categoria.Eliminar_categoriaRequest();
            inValue.id = id;
            Desk.Service_Categoria.Eliminar_categoriaResponse retVal = ((Desk.Service_Categoria.CategoriaService)(this)).Eliminar_categoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Eliminar_categoriaResponse> Desk.Service_Categoria.CategoriaService.Eliminar_categoriaAsync(Desk.Service_Categoria.Eliminar_categoriaRequest request) {
            return base.Channel.Eliminar_categoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Categoria.Eliminar_categoriaResponse> Eliminar_categoriaAsync(int id) {
            Desk.Service_Categoria.Eliminar_categoriaRequest inValue = new Desk.Service_Categoria.Eliminar_categoriaRequest();
            inValue.id = id;
            return ((Desk.Service_Categoria.CategoriaService)(this)).Eliminar_categoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Categoria.Crear_categoriaResponse Desk.Service_Categoria.CategoriaService.Crear_categoria(Desk.Service_Categoria.Crear_categoriaRequest request) {
            return base.Channel.Crear_categoria(request);
        }
        
        public string Crear_categoria(int id, string desc) {
            Desk.Service_Categoria.Crear_categoriaRequest inValue = new Desk.Service_Categoria.Crear_categoriaRequest();
            inValue.id = id;
            inValue.desc = desc;
            Desk.Service_Categoria.Crear_categoriaResponse retVal = ((Desk.Service_Categoria.CategoriaService)(this)).Crear_categoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Crear_categoriaResponse> Desk.Service_Categoria.CategoriaService.Crear_categoriaAsync(Desk.Service_Categoria.Crear_categoriaRequest request) {
            return base.Channel.Crear_categoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Categoria.Crear_categoriaResponse> Crear_categoriaAsync(int id, string desc) {
            Desk.Service_Categoria.Crear_categoriaRequest inValue = new Desk.Service_Categoria.Crear_categoriaRequest();
            inValue.id = id;
            inValue.desc = desc;
            return ((Desk.Service_Categoria.CategoriaService)(this)).Crear_categoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Categoria.Listado_categoriasResponse Desk.Service_Categoria.CategoriaService.Listado_categorias(Desk.Service_Categoria.Listado_categoriasRequest request) {
            return base.Channel.Listado_categorias(request);
        }
        
        public Desk.Service_Categoria.categoria[] Listado_categorias() {
            Desk.Service_Categoria.Listado_categoriasRequest inValue = new Desk.Service_Categoria.Listado_categoriasRequest();
            Desk.Service_Categoria.Listado_categoriasResponse retVal = ((Desk.Service_Categoria.CategoriaService)(this)).Listado_categorias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Categoria.Listado_categoriasResponse> Desk.Service_Categoria.CategoriaService.Listado_categoriasAsync(Desk.Service_Categoria.Listado_categoriasRequest request) {
            return base.Channel.Listado_categoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Categoria.Listado_categoriasResponse> Listado_categoriasAsync() {
            Desk.Service_Categoria.Listado_categoriasRequest inValue = new Desk.Service_Categoria.Listado_categoriasRequest();
            return ((Desk.Service_Categoria.CategoriaService)(this)).Listado_categoriasAsync(inValue);
        }
    }
}
