//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Service_OfertaVista {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_OfertaVista.OfertaVistaService")]
    public interface OfertaVistaService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Eliminar_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Eliminar_oferta_visitasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse Eliminar_oferta_visitas(Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Eliminar_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Eliminar_oferta_visitasResponse")]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse> Eliminar_oferta_visitasAsync(Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Crear_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Crear_oferta_visitasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_OfertaVista.Crear_oferta_visitasResponse Crear_oferta_visitas(Desk.Service_OfertaVista.Crear_oferta_visitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Crear_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Crear_oferta_visitasResponse")]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Crear_oferta_visitasResponse> Crear_oferta_visitasAsync(Desk.Service_OfertaVista.Crear_oferta_visitasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Listado_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Listado_oferta_visitasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_OfertaVista.Listado_oferta_visitasResponse Listado_oferta_visitas(Desk.Service_OfertaVista.Listado_oferta_visitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/OfertaVistaService/Listado_oferta_visitasRequest", ReplyAction="http://Servicios/OfertaVistaService/Listado_oferta_visitasResponse")]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Listado_oferta_visitasResponse> Listado_oferta_visitasAsync(Desk.Service_OfertaVista.Listado_oferta_visitasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_oferta_visitas", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_oferta_visitasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public Eliminar_oferta_visitasRequest() {
        }
        
        public Eliminar_oferta_visitasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_oferta_visitasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_oferta_visitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Eliminar_oferta_visitasResponse() {
        }
        
        public Eliminar_oferta_visitasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_oferta_visitas", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_oferta_visitasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_vista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_oferta_visita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_oferta;
        
        public Crear_oferta_visitasRequest() {
        }
        
        public Crear_oferta_visitasRequest(System.DateTime fecha_vista, int id_oferta_visita, int id_cliente, int id_oferta) {
            this.fecha_vista = fecha_vista;
            this.id_oferta_visita = id_oferta_visita;
            this.id_cliente = id_cliente;
            this.id_oferta = id_oferta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_oferta_visitasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_oferta_visitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Crear_oferta_visitasResponse() {
        }
        
        public Crear_oferta_visitasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class ofertasVisitas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteIdClienteField;
        
        private System.DateTime fechaVisitaField;
        
        private bool fechaVisitaFieldSpecified;
        
        private decimal idOfertasVisitasField;
        
        private bool idOfertasVisitasFieldSpecified;
        
        private oferta ofertaIdOfertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente clienteIdCliente {
            get {
                return this.clienteIdClienteField;
            }
            set {
                this.clienteIdClienteField = value;
                this.RaisePropertyChanged("clienteIdCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaVisita {
            get {
                return this.fechaVisitaField;
            }
            set {
                this.fechaVisitaField = value;
                this.RaisePropertyChanged("fechaVisita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVisitaSpecified {
            get {
                return this.fechaVisitaFieldSpecified;
            }
            set {
                this.fechaVisitaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVisitaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal idOfertasVisitas {
            get {
                return this.idOfertasVisitasField;
            }
            set {
                this.idOfertasVisitasField = value;
                this.RaisePropertyChanged("idOfertasVisitas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOfertasVisitasSpecified {
            get {
                return this.idOfertasVisitasFieldSpecified;
            }
            set {
                this.idOfertasVisitasFieldSpecified = value;
                this.RaisePropertyChanged("idOfertasVisitasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public oferta ofertaIdOferta {
            get {
                return this.ofertaIdOfertaField;
            }
            set {
                this.ofertaIdOfertaField = value;
                this.RaisePropertyChanged("ofertaIdOferta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort aceptaInformativoField;
        
        private bool aceptaInformativoFieldSpecified;
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private ciudad ciudadIdCiudadField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estado estadoIdEstadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private decimal idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private persona personaIdpersonaField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort aceptaInformativo {
            get {
                return this.aceptaInformativoField;
            }
            set {
                this.aceptaInformativoField = value;
                this.RaisePropertyChanged("aceptaInformativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aceptaInformativoSpecified {
            get {
                return this.aceptaInformativoFieldSpecified;
            }
            set {
                this.aceptaInformativoFieldSpecified = value;
                this.RaisePropertyChanged("aceptaInformativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciudad ciudadIdCiudad {
            get {
                return this.ciudadIdCiudadField;
            }
            set {
                this.ciudadIdCiudadField = value;
                this.RaisePropertyChanged("ciudadIdCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public persona personaIdpersona {
            get {
                return this.personaIdpersonaField;
            }
            set {
                this.personaIdpersonaField = value;
                this.RaisePropertyChanged("personaIdpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idCiudadField;
        
        private bool idCiudadFieldSpecified;
        
        private string nombreField;
        
        private region regionIdRegionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("idCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCiudadSpecified {
            get {
                return this.idCiudadFieldSpecified;
            }
            set {
                this.idCiudadFieldSpecified = value;
                this.RaisePropertyChanged("idCiudadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public region regionIdRegion {
            get {
                return this.regionIdRegionField;
            }
            set {
                this.regionIdRegionField = value;
                this.RaisePropertyChanged("regionIdRegion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idRegionField;
        
        private bool idRegionFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idRegion {
            get {
                return this.idRegionField;
            }
            set {
                this.idRegionField = value;
                this.RaisePropertyChanged("idRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegionSpecified {
            get {
                return this.idRegionFieldSpecified;
            }
            set {
                this.idRegionFieldSpecified = value;
                this.RaisePropertyChanged("idRegionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class informativo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idInformativoField;
        
        private bool idInformativoFieldSpecified;
        
        private oferta ofertaIdOfertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idInformativo {
            get {
                return this.idInformativoField;
            }
            set {
                this.idInformativoField = value;
                this.RaisePropertyChanged("idInformativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idInformativoSpecified {
            get {
                return this.idInformativoFieldSpecified;
            }
            set {
                this.idInformativoFieldSpecified = value;
                this.RaisePropertyChanged("idInformativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public oferta ofertaIdOferta {
            get {
                return this.ofertaIdOfertaField;
            }
            set {
                this.ofertaIdOfertaField = value;
                this.RaisePropertyChanged("ofertaIdOferta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class oferta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private string descripcionField;
        
        private estado estadoIdEstadoField;
        
        private decimal idOfertaField;
        
        private bool idOfertaFieldSpecified;
        
        private informativo informativoField;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private string maximoCompraField;
        
        private string minimoCompraField;
        
        private string nombreField;
        
        private string numeroVisitasField;
        
        private string precioNormalField;
        
        private string precioOfertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal idOferta {
            get {
                return this.idOfertaField;
            }
            set {
                this.idOfertaField = value;
                this.RaisePropertyChanged("idOferta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOfertaSpecified {
            get {
                return this.idOfertaFieldSpecified;
            }
            set {
                this.idOfertaFieldSpecified = value;
                this.RaisePropertyChanged("idOfertaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public informativo informativo {
            get {
                return this.informativoField;
            }
            set {
                this.informativoField = value;
                this.RaisePropertyChanged("informativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=6)]
        public string maximoCompra {
            get {
                return this.maximoCompraField;
            }
            set {
                this.maximoCompraField = value;
                this.RaisePropertyChanged("maximoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string minimoCompra {
            get {
                return this.minimoCompraField;
            }
            set {
                this.minimoCompraField = value;
                this.RaisePropertyChanged("minimoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=9)]
        public string numeroVisitas {
            get {
                return this.numeroVisitasField;
            }
            set {
                this.numeroVisitasField = value;
                this.RaisePropertyChanged("numeroVisitas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string precioNormal {
            get {
                return this.precioNormalField;
            }
            set {
                this.precioNormalField = value;
                this.RaisePropertyChanged("precioNormal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string precioOferta {
            get {
                return this.precioOfertaField;
            }
            set {
                this.precioOfertaField = value;
                this.RaisePropertyChanged("precioOferta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class sexo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idSexoField;
        
        private bool idSexoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idSexo {
            get {
                return this.idSexoField;
            }
            set {
                this.idSexoField = value;
                this.RaisePropertyChanged("idSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSexoSpecified {
            get {
                return this.idSexoFieldSpecified;
            }
            set {
                this.idSexoFieldSpecified = value;
                this.RaisePropertyChanged("idSexoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private decimal idpersonaField;
        
        private bool idpersonaFieldSpecified;
        
        private string nombreField;
        
        private string rutField;
        
        private sexo sexoIdSexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idpersona {
            get {
                return this.idpersonaField;
            }
            set {
                this.idpersonaField = value;
                this.RaisePropertyChanged("idpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idpersonaSpecified {
            get {
                return this.idpersonaFieldSpecified;
            }
            set {
                this.idpersonaFieldSpecified = value;
                this.RaisePropertyChanged("idpersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sexo sexoIdSexo {
            get {
                return this.sexoIdSexoField;
            }
            set {
                this.sexoIdSexoField = value;
                this.RaisePropertyChanged("sexoIdSexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_oferta_visitas", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_oferta_visitasRequest {
        
        public Listado_oferta_visitasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_oferta_visitasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_oferta_visitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Desk.Service_OfertaVista.ofertasVisitas[] @return;
        
        public Listado_oferta_visitasResponse() {
        }
        
        public Listado_oferta_visitasResponse(Desk.Service_OfertaVista.ofertasVisitas[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfertaVistaServiceChannel : Desk.Service_OfertaVista.OfertaVistaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaVistaServiceClient : System.ServiceModel.ClientBase<Desk.Service_OfertaVista.OfertaVistaService>, Desk.Service_OfertaVista.OfertaVistaService {
        
        public OfertaVistaServiceClient() {
        }
        
        public OfertaVistaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaVistaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVistaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaVistaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse Desk.Service_OfertaVista.OfertaVistaService.Eliminar_oferta_visitas(Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest request) {
            return base.Channel.Eliminar_oferta_visitas(request);
        }
        
        public string Eliminar_oferta_visitas(int id) {
            Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest();
            inValue.id = id;
            Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse retVal = ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Eliminar_oferta_visitas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse> Desk.Service_OfertaVista.OfertaVistaService.Eliminar_oferta_visitasAsync(Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest request) {
            return base.Channel.Eliminar_oferta_visitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_OfertaVista.Eliminar_oferta_visitasResponse> Eliminar_oferta_visitasAsync(int id) {
            Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Eliminar_oferta_visitasRequest();
            inValue.id = id;
            return ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Eliminar_oferta_visitasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_OfertaVista.Crear_oferta_visitasResponse Desk.Service_OfertaVista.OfertaVistaService.Crear_oferta_visitas(Desk.Service_OfertaVista.Crear_oferta_visitasRequest request) {
            return base.Channel.Crear_oferta_visitas(request);
        }
        
        public string Crear_oferta_visitas(System.DateTime fecha_vista, int id_oferta_visita, int id_cliente, int id_oferta) {
            Desk.Service_OfertaVista.Crear_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Crear_oferta_visitasRequest();
            inValue.fecha_vista = fecha_vista;
            inValue.id_oferta_visita = id_oferta_visita;
            inValue.id_cliente = id_cliente;
            inValue.id_oferta = id_oferta;
            Desk.Service_OfertaVista.Crear_oferta_visitasResponse retVal = ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Crear_oferta_visitas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Crear_oferta_visitasResponse> Desk.Service_OfertaVista.OfertaVistaService.Crear_oferta_visitasAsync(Desk.Service_OfertaVista.Crear_oferta_visitasRequest request) {
            return base.Channel.Crear_oferta_visitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_OfertaVista.Crear_oferta_visitasResponse> Crear_oferta_visitasAsync(System.DateTime fecha_vista, int id_oferta_visita, int id_cliente, int id_oferta) {
            Desk.Service_OfertaVista.Crear_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Crear_oferta_visitasRequest();
            inValue.fecha_vista = fecha_vista;
            inValue.id_oferta_visita = id_oferta_visita;
            inValue.id_cliente = id_cliente;
            inValue.id_oferta = id_oferta;
            return ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Crear_oferta_visitasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_OfertaVista.Listado_oferta_visitasResponse Desk.Service_OfertaVista.OfertaVistaService.Listado_oferta_visitas(Desk.Service_OfertaVista.Listado_oferta_visitasRequest request) {
            return base.Channel.Listado_oferta_visitas(request);
        }
        
        public Desk.Service_OfertaVista.ofertasVisitas[] Listado_oferta_visitas() {
            Desk.Service_OfertaVista.Listado_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Listado_oferta_visitasRequest();
            Desk.Service_OfertaVista.Listado_oferta_visitasResponse retVal = ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Listado_oferta_visitas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_OfertaVista.Listado_oferta_visitasResponse> Desk.Service_OfertaVista.OfertaVistaService.Listado_oferta_visitasAsync(Desk.Service_OfertaVista.Listado_oferta_visitasRequest request) {
            return base.Channel.Listado_oferta_visitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_OfertaVista.Listado_oferta_visitasResponse> Listado_oferta_visitasAsync() {
            Desk.Service_OfertaVista.Listado_oferta_visitasRequest inValue = new Desk.Service_OfertaVista.Listado_oferta_visitasRequest();
            return ((Desk.Service_OfertaVista.OfertaVistaService)(this)).Listado_oferta_visitasAsync(inValue);
        }
    }
}
