//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Service_UsuarioOferta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_UsuarioOferta.UsuarioOfertaService")]
    public interface UsuarioOfertaService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Crear_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Crear_usuario_ofertaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse Crear_usuario_oferta(Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Crear_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Crear_usuario_ofertaResponse")]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse> Crear_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Eliminar_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Eliminar_usuario_ofertaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse Eliminar_usuario_oferta(Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Eliminar_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Eliminar_usuario_ofertaResponse")]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse> Eliminar_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Listado_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Listado_usuario_ofertaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse Listado_usuario_oferta(Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/UsuarioOfertaService/Listado_usuario_ofertaRequest", ReplyAction="http://Servicios/UsuarioOfertaService/Listado_usuario_ofertaResponse")]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse> Listado_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_usuario_oferta", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_usuario_ofertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_oferta;
        
        public Crear_usuario_ofertaRequest() {
        }
        
        public Crear_usuario_ofertaRequest(int id, string descripcion, int id_usuario, int id_oferta) {
            this.id = id;
            this.descripcion = descripcion;
            this.id_usuario = id_usuario;
            this.id_oferta = id_oferta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_usuario_ofertaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_usuario_ofertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Crear_usuario_ofertaResponse() {
        }
        
        public Crear_usuario_ofertaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_usuario_oferta", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_usuario_ofertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public Eliminar_usuario_ofertaRequest() {
        }
        
        public Eliminar_usuario_ofertaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_usuario_ofertaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_usuario_ofertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Eliminar_usuario_ofertaResponse() {
        }
        
        public Eliminar_usuario_ofertaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class usuariooferta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private oferta ofertaField;
        
        private usuario usuarioField;
        
        private usuarioofertaPK usuarioofertaPKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public oferta oferta {
            get {
                return this.ofertaField;
            }
            set {
                this.ofertaField = value;
                this.RaisePropertyChanged("oferta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public usuarioofertaPK usuarioofertaPK {
            get {
                return this.usuarioofertaPKField;
            }
            set {
                this.usuarioofertaPKField = value;
                this.RaisePropertyChanged("usuarioofertaPK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class oferta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private string descripcionField;
        
        private estado estadoIdEstadoField;
        
        private decimal idOfertaField;
        
        private bool idOfertaFieldSpecified;
        
        private informativo informativoField;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private string maximoCompraField;
        
        private string minimoCompraField;
        
        private string nombreField;
        
        private string numeroVisitasField;
        
        private string precioNormalField;
        
        private string precioOfertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal idOferta {
            get {
                return this.idOfertaField;
            }
            set {
                this.idOfertaField = value;
                this.RaisePropertyChanged("idOferta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOfertaSpecified {
            get {
                return this.idOfertaFieldSpecified;
            }
            set {
                this.idOfertaFieldSpecified = value;
                this.RaisePropertyChanged("idOfertaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public informativo informativo {
            get {
                return this.informativoField;
            }
            set {
                this.informativoField = value;
                this.RaisePropertyChanged("informativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=6)]
        public string maximoCompra {
            get {
                return this.maximoCompraField;
            }
            set {
                this.maximoCompraField = value;
                this.RaisePropertyChanged("maximoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string minimoCompra {
            get {
                return this.minimoCompraField;
            }
            set {
                this.minimoCompraField = value;
                this.RaisePropertyChanged("minimoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=9)]
        public string numeroVisitas {
            get {
                return this.numeroVisitasField;
            }
            set {
                this.numeroVisitasField = value;
                this.RaisePropertyChanged("numeroVisitas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string precioNormal {
            get {
                return this.precioNormalField;
            }
            set {
                this.precioNormalField = value;
                this.RaisePropertyChanged("precioNormal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string precioOferta {
            get {
                return this.precioOfertaField;
            }
            set {
                this.precioOfertaField = value;
                this.RaisePropertyChanged("precioOferta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class usuarioofertaPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idusuarioofertaField;
        
        private string ofertaIdOfertaField;
        
        private string usuarioIdUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string idusuariooferta {
            get {
                return this.idusuarioofertaField;
            }
            set {
                this.idusuarioofertaField = value;
                this.RaisePropertyChanged("idusuariooferta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string ofertaIdOferta {
            get {
                return this.ofertaIdOfertaField;
            }
            set {
                this.ofertaIdOfertaField = value;
                this.RaisePropertyChanged("ofertaIdOferta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string usuarioIdUsuario {
            get {
                return this.usuarioIdUsuarioField;
            }
            set {
                this.usuarioIdUsuarioField = value;
                this.RaisePropertyChanged("usuarioIdUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class sexo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idSexoField;
        
        private bool idSexoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idSexo {
            get {
                return this.idSexoField;
            }
            set {
                this.idSexoField = value;
                this.RaisePropertyChanged("idSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSexoSpecified {
            get {
                return this.idSexoFieldSpecified;
            }
            set {
                this.idSexoFieldSpecified = value;
                this.RaisePropertyChanged("idSexoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private decimal idpersonaField;
        
        private bool idpersonaFieldSpecified;
        
        private string nombreField;
        
        private string rutField;
        
        private sexo sexoIdSexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idpersona {
            get {
                return this.idpersonaField;
            }
            set {
                this.idpersonaField = value;
                this.RaisePropertyChanged("idpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idpersonaSpecified {
            get {
                return this.idpersonaFieldSpecified;
            }
            set {
                this.idpersonaFieldSpecified = value;
                this.RaisePropertyChanged("idpersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sexo sexoIdSexo {
            get {
                return this.sexoIdSexoField;
            }
            set {
                this.sexoIdSexoField = value;
                this.RaisePropertyChanged("sexoIdSexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idcargoField;
        
        private bool idcargoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idcargo {
            get {
                return this.idcargoField;
            }
            set {
                this.idcargoField = value;
                this.RaisePropertyChanged("idcargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idcargoSpecified {
            get {
                return this.idcargoFieldSpecified;
            }
            set {
                this.idcargoFieldSpecified = value;
                this.RaisePropertyChanged("idcargoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private cargo cargoIdcargoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estado estadoIdEstadoField;
        
        private System.DateTime fechacreadoField;
        
        private bool fechacreadoFieldSpecified;
        
        private decimal idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private persona personaIdpersonaField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargoIdcargo {
            get {
                return this.cargoIdcargoField;
            }
            set {
                this.cargoIdcargoField = value;
                this.RaisePropertyChanged("cargoIdcargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechacreado {
            get {
                return this.fechacreadoField;
            }
            set {
                this.fechacreadoField = value;
                this.RaisePropertyChanged("fechacreado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechacreadoSpecified {
            get {
                return this.fechacreadoFieldSpecified;
            }
            set {
                this.fechacreadoFieldSpecified = value;
                this.RaisePropertyChanged("fechacreadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public persona personaIdpersona {
            get {
                return this.personaIdpersonaField;
            }
            set {
                this.personaIdpersonaField = value;
                this.RaisePropertyChanged("personaIdpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class informativo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idInformativoField;
        
        private bool idInformativoFieldSpecified;
        
        private oferta ofertaIdOfertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idInformativo {
            get {
                return this.idInformativoField;
            }
            set {
                this.idInformativoField = value;
                this.RaisePropertyChanged("idInformativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idInformativoSpecified {
            get {
                return this.idInformativoFieldSpecified;
            }
            set {
                this.idInformativoFieldSpecified = value;
                this.RaisePropertyChanged("idInformativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public oferta ofertaIdOferta {
            get {
                return this.ofertaIdOfertaField;
            }
            set {
                this.ofertaIdOfertaField = value;
                this.RaisePropertyChanged("ofertaIdOferta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_usuario_oferta", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_usuario_ofertaRequest {
        
        public Listado_usuario_ofertaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_usuario_ofertaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_usuario_ofertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Desk.Service_UsuarioOferta.usuariooferta[] @return;
        
        public Listado_usuario_ofertaResponse() {
        }
        
        public Listado_usuario_ofertaResponse(Desk.Service_UsuarioOferta.usuariooferta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioOfertaServiceChannel : Desk.Service_UsuarioOferta.UsuarioOfertaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioOfertaServiceClient : System.ServiceModel.ClientBase<Desk.Service_UsuarioOferta.UsuarioOfertaService>, Desk.Service_UsuarioOferta.UsuarioOfertaService {
        
        public UsuarioOfertaServiceClient() {
        }
        
        public UsuarioOfertaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioOfertaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioOfertaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioOfertaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse Desk.Service_UsuarioOferta.UsuarioOfertaService.Crear_usuario_oferta(Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest request) {
            return base.Channel.Crear_usuario_oferta(request);
        }
        
        public string Crear_usuario_oferta(int id, string descripcion, int id_usuario, int id_oferta) {
            Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest();
            inValue.id = id;
            inValue.descripcion = descripcion;
            inValue.id_usuario = id_usuario;
            inValue.id_oferta = id_oferta;
            Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse retVal = ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Crear_usuario_oferta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse> Desk.Service_UsuarioOferta.UsuarioOfertaService.Crear_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest request) {
            return base.Channel.Crear_usuario_ofertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Crear_usuario_ofertaResponse> Crear_usuario_ofertaAsync(int id, string descripcion, int id_usuario, int id_oferta) {
            Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Crear_usuario_ofertaRequest();
            inValue.id = id;
            inValue.descripcion = descripcion;
            inValue.id_usuario = id_usuario;
            inValue.id_oferta = id_oferta;
            return ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Crear_usuario_ofertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse Desk.Service_UsuarioOferta.UsuarioOfertaService.Eliminar_usuario_oferta(Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest request) {
            return base.Channel.Eliminar_usuario_oferta(request);
        }
        
        public string Eliminar_usuario_oferta(int id) {
            Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest();
            inValue.id = id;
            Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse retVal = ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Eliminar_usuario_oferta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse> Desk.Service_UsuarioOferta.UsuarioOfertaService.Eliminar_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest request) {
            return base.Channel.Eliminar_usuario_ofertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaResponse> Eliminar_usuario_ofertaAsync(int id) {
            Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Eliminar_usuario_ofertaRequest();
            inValue.id = id;
            return ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Eliminar_usuario_ofertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse Desk.Service_UsuarioOferta.UsuarioOfertaService.Listado_usuario_oferta(Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest request) {
            return base.Channel.Listado_usuario_oferta(request);
        }
        
        public Desk.Service_UsuarioOferta.usuariooferta[] Listado_usuario_oferta() {
            Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest();
            Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse retVal = ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Listado_usuario_oferta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse> Desk.Service_UsuarioOferta.UsuarioOfertaService.Listado_usuario_ofertaAsync(Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest request) {
            return base.Channel.Listado_usuario_ofertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_UsuarioOferta.Listado_usuario_ofertaResponse> Listado_usuario_ofertaAsync() {
            Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest inValue = new Desk.Service_UsuarioOferta.Listado_usuario_ofertaRequest();
            return ((Desk.Service_UsuarioOferta.UsuarioOfertaService)(this)).Listado_usuario_ofertaAsync(inValue);
        }
    }
}
