//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Service_Reporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_Reporte.ReporteService")]
    public interface ReporteService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Listado_reportesRequest", ReplyAction="http://Servicios/ReporteService/Listado_reportesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Reporte.Listado_reportesResponse Listado_reportes(Desk.Service_Reporte.Listado_reportesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Listado_reportesRequest", ReplyAction="http://Servicios/ReporteService/Listado_reportesResponse")]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Listado_reportesResponse> Listado_reportesAsync(Desk.Service_Reporte.Listado_reportesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Eliminar_reporteRequest", ReplyAction="http://Servicios/ReporteService/Eliminar_reporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Reporte.Eliminar_reporteResponse Eliminar_reporte(Desk.Service_Reporte.Eliminar_reporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Eliminar_reporteRequest", ReplyAction="http://Servicios/ReporteService/Eliminar_reporteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Eliminar_reporteResponse> Eliminar_reporteAsync(Desk.Service_Reporte.Eliminar_reporteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Crear_reporteRequest", ReplyAction="http://Servicios/ReporteService/Crear_reporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Reporte.Crear_reporteResponse Crear_reporte(Desk.Service_Reporte.Crear_reporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Crear_reporteRequest", ReplyAction="http://Servicios/ReporteService/Crear_reporteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Crear_reporteResponse> Crear_reporteAsync(Desk.Service_Reporte.Crear_reporteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Modificar_reporteRequest", ReplyAction="http://Servicios/ReporteService/Modificar_reporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Reporte.Modificar_reporteResponse Modificar_reporte(Desk.Service_Reporte.Modificar_reporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ReporteService/Modificar_reporteRequest", ReplyAction="http://Servicios/ReporteService/Modificar_reporteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Modificar_reporteResponse> Modificar_reporteAsync(Desk.Service_Reporte.Modificar_reporteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class puntos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteIdClienteField;
        
        private System.DateTime fechaActualizacionField;
        
        private bool fechaActualizacionFieldSpecified;
        
        private decimal idPuntosField;
        
        private bool idPuntosFieldSpecified;
        
        private string puntosCanjeadosField;
        
        private string totalPuntosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente clienteIdCliente {
            get {
                return this.clienteIdClienteField;
            }
            set {
                this.clienteIdClienteField = value;
                this.RaisePropertyChanged("clienteIdCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaActualizacionSpecified {
            get {
                return this.fechaActualizacionFieldSpecified;
            }
            set {
                this.fechaActualizacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaActualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal idPuntos {
            get {
                return this.idPuntosField;
            }
            set {
                this.idPuntosField = value;
                this.RaisePropertyChanged("idPuntos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPuntosSpecified {
            get {
                return this.idPuntosFieldSpecified;
            }
            set {
                this.idPuntosFieldSpecified = value;
                this.RaisePropertyChanged("idPuntosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string puntosCanjeados {
            get {
                return this.puntosCanjeadosField;
            }
            set {
                this.puntosCanjeadosField = value;
                this.RaisePropertyChanged("puntosCanjeados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string totalPuntos {
            get {
                return this.totalPuntosField;
            }
            set {
                this.totalPuntosField = value;
                this.RaisePropertyChanged("totalPuntos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort aceptaInformativoField;
        
        private bool aceptaInformativoFieldSpecified;
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private ciudad ciudadIdCiudadField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estado estadoIdEstadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private decimal idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private persona personaIdpersonaField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort aceptaInformativo {
            get {
                return this.aceptaInformativoField;
            }
            set {
                this.aceptaInformativoField = value;
                this.RaisePropertyChanged("aceptaInformativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aceptaInformativoSpecified {
            get {
                return this.aceptaInformativoFieldSpecified;
            }
            set {
                this.aceptaInformativoFieldSpecified = value;
                this.RaisePropertyChanged("aceptaInformativoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciudad ciudadIdCiudad {
            get {
                return this.ciudadIdCiudadField;
            }
            set {
                this.ciudadIdCiudadField = value;
                this.RaisePropertyChanged("ciudadIdCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public persona personaIdpersona {
            get {
                return this.personaIdpersonaField;
            }
            set {
                this.personaIdpersonaField = value;
                this.RaisePropertyChanged("personaIdpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idCiudadField;
        
        private bool idCiudadFieldSpecified;
        
        private string nombreField;
        
        private region regionIdRegionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("idCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCiudadSpecified {
            get {
                return this.idCiudadFieldSpecified;
            }
            set {
                this.idCiudadFieldSpecified = value;
                this.RaisePropertyChanged("idCiudadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public region regionIdRegion {
            get {
                return this.regionIdRegionField;
            }
            set {
                this.regionIdRegionField = value;
                this.RaisePropertyChanged("regionIdRegion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idRegionField;
        
        private bool idRegionFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idRegion {
            get {
                return this.idRegionField;
            }
            set {
                this.idRegionField = value;
                this.RaisePropertyChanged("idRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegionSpecified {
            get {
                return this.idRegionFieldSpecified;
            }
            set {
                this.idRegionFieldSpecified = value;
                this.RaisePropertyChanged("idRegionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class sexo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idSexoField;
        
        private bool idSexoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idSexo {
            get {
                return this.idSexoField;
            }
            set {
                this.idSexoField = value;
                this.RaisePropertyChanged("idSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSexoSpecified {
            get {
                return this.idSexoFieldSpecified;
            }
            set {
                this.idSexoFieldSpecified = value;
                this.RaisePropertyChanged("idSexoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private decimal idpersonaField;
        
        private bool idpersonaFieldSpecified;
        
        private string nombreField;
        
        private string rutField;
        
        private sexo sexoIdSexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idpersona {
            get {
                return this.idpersonaField;
            }
            set {
                this.idpersonaField = value;
                this.RaisePropertyChanged("idpersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idpersonaSpecified {
            get {
                return this.idpersonaFieldSpecified;
            }
            set {
                this.idpersonaFieldSpecified = value;
                this.RaisePropertyChanged("idpersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sexo sexoIdSexo {
            get {
                return this.sexoIdSexoField;
            }
            set {
                this.sexoIdSexoField = value;
                this.RaisePropertyChanged("sexoIdSexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_reportes", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_reportesRequest {
        
        public Listado_reportesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_reportesResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_reportesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Desk.Service_Reporte.puntos[] @return;
        
        public Listado_reportesResponse() {
        }
        
        public Listado_reportesResponse(Desk.Service_Reporte.puntos[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_reporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_reporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public Eliminar_reporteRequest() {
        }
        
        public Eliminar_reporteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_reporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_reporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Eliminar_reporteResponse() {
        }
        
        public Eliminar_reporteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_reporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_reporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int local_id;
        
        public Crear_reporteRequest() {
        }
        
        public Crear_reporteRequest(int id, int local_id) {
            this.id = id;
            this.local_id = local_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_reporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_reporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Crear_reporteResponse() {
        }
        
        public Crear_reporteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_reporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_reporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int local_id;
        
        public Modificar_reporteRequest() {
        }
        
        public Modificar_reporteRequest(int id, int local_id) {
            this.id = id;
            this.local_id = local_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_reporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_reporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Modificar_reporteResponse() {
        }
        
        public Modificar_reporteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteServiceChannel : Desk.Service_Reporte.ReporteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteServiceClient : System.ServiceModel.ClientBase<Desk.Service_Reporte.ReporteService>, Desk.Service_Reporte.ReporteService {
        
        public ReporteServiceClient() {
        }
        
        public ReporteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Reporte.Listado_reportesResponse Desk.Service_Reporte.ReporteService.Listado_reportes(Desk.Service_Reporte.Listado_reportesRequest request) {
            return base.Channel.Listado_reportes(request);
        }
        
        public Desk.Service_Reporte.puntos[] Listado_reportes() {
            Desk.Service_Reporte.Listado_reportesRequest inValue = new Desk.Service_Reporte.Listado_reportesRequest();
            Desk.Service_Reporte.Listado_reportesResponse retVal = ((Desk.Service_Reporte.ReporteService)(this)).Listado_reportes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Listado_reportesResponse> Desk.Service_Reporte.ReporteService.Listado_reportesAsync(Desk.Service_Reporte.Listado_reportesRequest request) {
            return base.Channel.Listado_reportesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Reporte.Listado_reportesResponse> Listado_reportesAsync() {
            Desk.Service_Reporte.Listado_reportesRequest inValue = new Desk.Service_Reporte.Listado_reportesRequest();
            return ((Desk.Service_Reporte.ReporteService)(this)).Listado_reportesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Reporte.Eliminar_reporteResponse Desk.Service_Reporte.ReporteService.Eliminar_reporte(Desk.Service_Reporte.Eliminar_reporteRequest request) {
            return base.Channel.Eliminar_reporte(request);
        }
        
        public string Eliminar_reporte(int id) {
            Desk.Service_Reporte.Eliminar_reporteRequest inValue = new Desk.Service_Reporte.Eliminar_reporteRequest();
            inValue.id = id;
            Desk.Service_Reporte.Eliminar_reporteResponse retVal = ((Desk.Service_Reporte.ReporteService)(this)).Eliminar_reporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Eliminar_reporteResponse> Desk.Service_Reporte.ReporteService.Eliminar_reporteAsync(Desk.Service_Reporte.Eliminar_reporteRequest request) {
            return base.Channel.Eliminar_reporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Reporte.Eliminar_reporteResponse> Eliminar_reporteAsync(int id) {
            Desk.Service_Reporte.Eliminar_reporteRequest inValue = new Desk.Service_Reporte.Eliminar_reporteRequest();
            inValue.id = id;
            return ((Desk.Service_Reporte.ReporteService)(this)).Eliminar_reporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Reporte.Crear_reporteResponse Desk.Service_Reporte.ReporteService.Crear_reporte(Desk.Service_Reporte.Crear_reporteRequest request) {
            return base.Channel.Crear_reporte(request);
        }
        
        public string Crear_reporte(int id, int local_id) {
            Desk.Service_Reporte.Crear_reporteRequest inValue = new Desk.Service_Reporte.Crear_reporteRequest();
            inValue.id = id;
            inValue.local_id = local_id;
            Desk.Service_Reporte.Crear_reporteResponse retVal = ((Desk.Service_Reporte.ReporteService)(this)).Crear_reporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Crear_reporteResponse> Desk.Service_Reporte.ReporteService.Crear_reporteAsync(Desk.Service_Reporte.Crear_reporteRequest request) {
            return base.Channel.Crear_reporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Reporte.Crear_reporteResponse> Crear_reporteAsync(int id, int local_id) {
            Desk.Service_Reporte.Crear_reporteRequest inValue = new Desk.Service_Reporte.Crear_reporteRequest();
            inValue.id = id;
            inValue.local_id = local_id;
            return ((Desk.Service_Reporte.ReporteService)(this)).Crear_reporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Reporte.Modificar_reporteResponse Desk.Service_Reporte.ReporteService.Modificar_reporte(Desk.Service_Reporte.Modificar_reporteRequest request) {
            return base.Channel.Modificar_reporte(request);
        }
        
        public string Modificar_reporte(int id, int local_id) {
            Desk.Service_Reporte.Modificar_reporteRequest inValue = new Desk.Service_Reporte.Modificar_reporteRequest();
            inValue.id = id;
            inValue.local_id = local_id;
            Desk.Service_Reporte.Modificar_reporteResponse retVal = ((Desk.Service_Reporte.ReporteService)(this)).Modificar_reporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Reporte.Modificar_reporteResponse> Desk.Service_Reporte.ReporteService.Modificar_reporteAsync(Desk.Service_Reporte.Modificar_reporteRequest request) {
            return base.Channel.Modificar_reporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Reporte.Modificar_reporteResponse> Modificar_reporteAsync(int id, int local_id) {
            Desk.Service_Reporte.Modificar_reporteRequest inValue = new Desk.Service_Reporte.Modificar_reporteRequest();
            inValue.id = id;
            inValue.local_id = local_id;
            return ((Desk.Service_Reporte.ReporteService)(this)).Modificar_reporteAsync(inValue);
        }
    }
}
