//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Service_Cliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_Cliente.ClienteService")]
    public interface ClienteService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/AutenticacionRequest", ReplyAction="http://Servicios/ClienteService/AutenticacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Listado_clientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutenticacionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Autenticacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_cliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Cliente.AutenticacionResponse1 Autenticacion(Desk.Service_Cliente.AutenticacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/AutenticacionRequest", ReplyAction="http://Servicios/ClienteService/AutenticacionResponse")]
        System.Threading.Tasks.Task<Desk.Service_Cliente.AutenticacionResponse1> AutenticacionAsync(Desk.Service_Cliente.AutenticacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Eliminar_clienteRequest", ReplyAction="http://Servicios/ClienteService/Eliminar_clienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Listado_clientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutenticacionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Autenticacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_cliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Cliente.Eliminar_clienteResponse1 Eliminar_cliente(Desk.Service_Cliente.Eliminar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Eliminar_clienteRequest", ReplyAction="http://Servicios/ClienteService/Eliminar_clienteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Eliminar_clienteResponse1> Eliminar_clienteAsync(Desk.Service_Cliente.Eliminar_clienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Crear_clienteRequest", ReplyAction="http://Servicios/ClienteService/Crear_clienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Listado_clientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutenticacionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Autenticacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_cliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Cliente.Crear_clienteResponse1 Crear_cliente(Desk.Service_Cliente.Crear_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Crear_clienteRequest", ReplyAction="http://Servicios/ClienteService/Crear_clienteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Crear_clienteResponse1> Crear_clienteAsync(Desk.Service_Cliente.Crear_clienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Listado_clientesRequest", ReplyAction="http://Servicios/ClienteService/Listado_clientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Listado_clientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutenticacionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Autenticacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_cliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Cliente.Listado_clientesResponse Listado_clientes(Desk.Service_Cliente.Listado_clientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Listado_clientesRequest", ReplyAction="http://Servicios/ClienteService/Listado_clientesResponse")]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Listado_clientesResponse> Listado_clientesAsync(Desk.Service_Cliente.Listado_clientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Modificar_clienteRequest", ReplyAction="http://Servicios/ClienteService/Modificar_clienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Modificar_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Listado_clientes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutenticacionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Autenticacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Crear_cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_clienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eliminar_cliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Desk.Service_Cliente.Modificar_clienteResponse1 Modificar_cliente(Desk.Service_Cliente.Modificar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ClienteService/Modificar_clienteRequest", ReplyAction="http://Servicios/ClienteService/Modificar_clienteResponse")]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Modificar_clienteResponse1> Modificar_clienteAsync(Desk.Service_Cliente.Modificar_clienteRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Modificar_clienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Modificar_cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime fecha_nacimientoField;
        
        private bool fecha_nacimientoFieldSpecified;
        
        private string correoField;
        
        private string passwordField;
        
        private int telefonoField;
        
        private string acepta_informativoField;
        
        private System.DateTime fecha_inicioField;
        
        private bool fecha_inicioFieldSpecified;
        
        private System.DateTime fecha_actualizacionField;
        
        private bool fecha_actualizacionFieldSpecified;
        
        private int id_ciudadField;
        
        private int id_estadoField;
        
        private int id_personaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("fecha_nacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_nacimientoSpecified {
            get {
                return this.fecha_nacimientoFieldSpecified;
            }
            set {
                this.fecha_nacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_nacimientoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string acepta_informativo {
            get {
                return this.acepta_informativoField;
            }
            set {
                this.acepta_informativoField = value;
                this.RaisePropertyChanged("acepta_informativo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
                this.RaisePropertyChanged("fecha_inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_inicioSpecified {
            get {
                return this.fecha_inicioFieldSpecified;
            }
            set {
                this.fecha_inicioFieldSpecified = value;
                this.RaisePropertyChanged("fecha_inicioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fecha_actualizacion {
            get {
                return this.fecha_actualizacionField;
            }
            set {
                this.fecha_actualizacionField = value;
                this.RaisePropertyChanged("fecha_actualizacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_actualizacionSpecified {
            get {
                return this.fecha_actualizacionFieldSpecified;
            }
            set {
                this.fecha_actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_actualizacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int id_ciudad {
            get {
                return this.id_ciudadField;
            }
            set {
                this.id_ciudadField = value;
                this.RaisePropertyChanged("id_ciudad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                this.id_estadoField = value;
                this.RaisePropertyChanged("id_estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int id_persona {
            get {
                return this.id_personaField;
            }
            set {
                this.id_personaField = value;
                this.RaisePropertyChanged("id_persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class sexo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idSexoField;
        
        private bool idSexoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idSexo {
            get {
                return this.idSexoField;
            }
            set {
                this.idSexoField = value;
                this.RaisePropertyChanged("idSexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSexoSpecified {
            get {
                return this.idSexoFieldSpecified;
            }
            set {
                this.idSexoFieldSpecified = value;
                this.RaisePropertyChanged("idSexoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private decimal idpersonaField;
        
        private bool idpersonaFieldSpecified;
        
        private string nombreField;
        
        private string rutField;
        
        private sexo sexoIdSexoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idpersona {
            get {
                return this.idpersonaField;
            }
            set {
                this.idpersonaField = value;
                this.RaisePropertyChanged("idpersona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idpersonaSpecified {
            get {
                return this.idpersonaFieldSpecified;
            }
            set {
                this.idpersonaFieldSpecified = value;
                this.RaisePropertyChanged("idpersonaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sexo sexoIdSexo {
            get {
                return this.sexoIdSexoField;
            }
            set {
                this.sexoIdSexoField = value;
                this.RaisePropertyChanged("sexoIdSexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idRegionField;
        
        private bool idRegionFieldSpecified;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idRegion {
            get {
                return this.idRegionField;
            }
            set {
                this.idRegionField = value;
                this.RaisePropertyChanged("idRegion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegionSpecified {
            get {
                return this.idRegionFieldSpecified;
            }
            set {
                this.idRegionFieldSpecified = value;
                this.RaisePropertyChanged("idRegionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idCiudadField;
        
        private bool idCiudadFieldSpecified;
        
        private string nombreField;
        
        private region regionIdRegionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("idCiudad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCiudadSpecified {
            get {
                return this.idCiudadFieldSpecified;
            }
            set {
                this.idCiudadFieldSpecified = value;
                this.RaisePropertyChanged("idCiudadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public region regionIdRegion {
            get {
                return this.regionIdRegionField;
            }
            set {
                this.regionIdRegionField = value;
                this.RaisePropertyChanged("regionIdRegion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort aceptaInformativoField;
        
        private bool aceptaInformativoFieldSpecified;
        
        private System.DateTime actualizacionField;
        
        private bool actualizacionFieldSpecified;
        
        private ciudad ciudadIdCiudadField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estado estadoIdEstadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private decimal idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private System.DateTime inicioField;
        
        private bool inicioFieldSpecified;
        
        private persona personaIdpersonaField;
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort aceptaInformativo {
            get {
                return this.aceptaInformativoField;
            }
            set {
                this.aceptaInformativoField = value;
                this.RaisePropertyChanged("aceptaInformativo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aceptaInformativoSpecified {
            get {
                return this.aceptaInformativoFieldSpecified;
            }
            set {
                this.aceptaInformativoFieldSpecified = value;
                this.RaisePropertyChanged("aceptaInformativoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime actualizacion {
            get {
                return this.actualizacionField;
            }
            set {
                this.actualizacionField = value;
                this.RaisePropertyChanged("actualizacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualizacionSpecified {
            get {
                return this.actualizacionFieldSpecified;
            }
            set {
                this.actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("actualizacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciudad ciudadIdCiudad {
            get {
                return this.ciudadIdCiudadField;
            }
            set {
                this.ciudadIdCiudadField = value;
                this.RaisePropertyChanged("ciudadIdCiudad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public estado estadoIdEstado {
            get {
                return this.estadoIdEstadoField;
            }
            set {
                this.estadoIdEstadoField = value;
                this.RaisePropertyChanged("estadoIdEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inicioSpecified {
            get {
                return this.inicioFieldSpecified;
            }
            set {
                this.inicioFieldSpecified = value;
                this.RaisePropertyChanged("inicioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public persona personaIdpersona {
            get {
                return this.personaIdpersonaField;
            }
            set {
                this.personaIdpersonaField = value;
                this.RaisePropertyChanged("personaIdpersona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Listado_clientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class AutenticacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string contrasenaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Crear_clienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Crear_cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime fecha_nacimientoField;
        
        private bool fecha_nacimientoFieldSpecified;
        
        private string correoField;
        
        private string passwordField;
        
        private int telefonoField;
        
        private string acepta_informativoField;
        
        private System.DateTime fecha_inicioField;
        
        private bool fecha_inicioFieldSpecified;
        
        private System.DateTime fecha_actualizacionField;
        
        private bool fecha_actualizacionFieldSpecified;
        
        private int id_ciudadField;
        
        private int id_estadoField;
        
        private int id_personaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("fecha_nacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_nacimientoSpecified {
            get {
                return this.fecha_nacimientoFieldSpecified;
            }
            set {
                this.fecha_nacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_nacimientoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string acepta_informativo {
            get {
                return this.acepta_informativoField;
            }
            set {
                this.acepta_informativoField = value;
                this.RaisePropertyChanged("acepta_informativo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
                this.RaisePropertyChanged("fecha_inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_inicioSpecified {
            get {
                return this.fecha_inicioFieldSpecified;
            }
            set {
                this.fecha_inicioFieldSpecified = value;
                this.RaisePropertyChanged("fecha_inicioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fecha_actualizacion {
            get {
                return this.fecha_actualizacionField;
            }
            set {
                this.fecha_actualizacionField = value;
                this.RaisePropertyChanged("fecha_actualizacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_actualizacionSpecified {
            get {
                return this.fecha_actualizacionFieldSpecified;
            }
            set {
                this.fecha_actualizacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_actualizacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int id_ciudad {
            get {
                return this.id_ciudadField;
            }
            set {
                this.id_ciudadField = value;
                this.RaisePropertyChanged("id_ciudad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                this.id_estadoField = value;
                this.RaisePropertyChanged("id_estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int id_persona {
            get {
                return this.id_personaField;
            }
            set {
                this.id_personaField = value;
                this.RaisePropertyChanged("id_persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Eliminar_clienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Eliminar_cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticacion", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class AutenticacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public AutenticacionRequest() {
        }
        
        public AutenticacionRequest(string correo, string contrasena) {
            this.correo = correo;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class AutenticacionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object @return;
        
        public AutenticacionResponse1() {
        }
        
        public AutenticacionResponse1(object @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_cliente", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public Eliminar_clienteRequest() {
        }
        
        public Eliminar_clienteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_clienteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Eliminar_clienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Eliminar_clienteResponse1() {
        }
        
        public Eliminar_clienteResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_cliente", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acepta_informativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_actualizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_persona;
        
        public Crear_clienteRequest() {
        }
        
        public Crear_clienteRequest(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            this.id = id;
            this.fecha_nacimiento = fecha_nacimiento;
            this.correo = correo;
            this.password = password;
            this.telefono = telefono;
            this.acepta_informativo = acepta_informativo;
            this.fecha_inicio = fecha_inicio;
            this.fecha_actualizacion = fecha_actualizacion;
            this.id_ciudad = id_ciudad;
            this.id_estado = id_estado;
            this.id_persona = id_persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crear_clienteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Crear_clienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Crear_clienteResponse1() {
        }
        
        public Crear_clienteResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_clientes", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_clientesRequest {
        
        public Listado_clientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listado_clientesResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Listado_clientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Desk.Service_Cliente.cliente[] @return;
        
        public Listado_clientesResponse() {
        }
        
        public Listado_clientesResponse(Desk.Service_Cliente.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_cliente", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acepta_informativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_actualizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_persona;
        
        public Modificar_clienteRequest() {
        }
        
        public Modificar_clienteRequest(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            this.id = id;
            this.fecha_nacimiento = fecha_nacimiento;
            this.correo = correo;
            this.password = password;
            this.telefono = telefono;
            this.acepta_informativo = acepta_informativo;
            this.fecha_inicio = fecha_inicio;
            this.fecha_actualizacion = fecha_actualizacion;
            this.id_ciudad = id_ciudad;
            this.id_estado = id_estado;
            this.id_persona = id_persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_clienteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class Modificar_clienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Modificar_clienteResponse1() {
        }
        
        public Modificar_clienteResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteServiceChannel : Desk.Service_Cliente.ClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<Desk.Service_Cliente.ClienteService>, Desk.Service_Cliente.ClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Cliente.AutenticacionResponse1 Desk.Service_Cliente.ClienteService.Autenticacion(Desk.Service_Cliente.AutenticacionRequest request) {
            return base.Channel.Autenticacion(request);
        }
        
        public object Autenticacion(string correo, string contrasena) {
            Desk.Service_Cliente.AutenticacionRequest inValue = new Desk.Service_Cliente.AutenticacionRequest();
            inValue.correo = correo;
            inValue.contrasena = contrasena;
            Desk.Service_Cliente.AutenticacionResponse1 retVal = ((Desk.Service_Cliente.ClienteService)(this)).Autenticacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Cliente.AutenticacionResponse1> Desk.Service_Cliente.ClienteService.AutenticacionAsync(Desk.Service_Cliente.AutenticacionRequest request) {
            return base.Channel.AutenticacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Cliente.AutenticacionResponse1> AutenticacionAsync(string correo, string contrasena) {
            Desk.Service_Cliente.AutenticacionRequest inValue = new Desk.Service_Cliente.AutenticacionRequest();
            inValue.correo = correo;
            inValue.contrasena = contrasena;
            return ((Desk.Service_Cliente.ClienteService)(this)).AutenticacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Cliente.Eliminar_clienteResponse1 Desk.Service_Cliente.ClienteService.Eliminar_cliente(Desk.Service_Cliente.Eliminar_clienteRequest request) {
            return base.Channel.Eliminar_cliente(request);
        }
        
        public string Eliminar_cliente(int id) {
            Desk.Service_Cliente.Eliminar_clienteRequest inValue = new Desk.Service_Cliente.Eliminar_clienteRequest();
            inValue.id = id;
            Desk.Service_Cliente.Eliminar_clienteResponse1 retVal = ((Desk.Service_Cliente.ClienteService)(this)).Eliminar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Eliminar_clienteResponse1> Desk.Service_Cliente.ClienteService.Eliminar_clienteAsync(Desk.Service_Cliente.Eliminar_clienteRequest request) {
            return base.Channel.Eliminar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Cliente.Eliminar_clienteResponse1> Eliminar_clienteAsync(int id) {
            Desk.Service_Cliente.Eliminar_clienteRequest inValue = new Desk.Service_Cliente.Eliminar_clienteRequest();
            inValue.id = id;
            return ((Desk.Service_Cliente.ClienteService)(this)).Eliminar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Cliente.Crear_clienteResponse1 Desk.Service_Cliente.ClienteService.Crear_cliente(Desk.Service_Cliente.Crear_clienteRequest request) {
            return base.Channel.Crear_cliente(request);
        }
        
        public string Crear_cliente(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            Desk.Service_Cliente.Crear_clienteRequest inValue = new Desk.Service_Cliente.Crear_clienteRequest();
            inValue.id = id;
            inValue.fecha_nacimiento = fecha_nacimiento;
            inValue.correo = correo;
            inValue.password = password;
            inValue.telefono = telefono;
            inValue.acepta_informativo = acepta_informativo;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_actualizacion = fecha_actualizacion;
            inValue.id_ciudad = id_ciudad;
            inValue.id_estado = id_estado;
            inValue.id_persona = id_persona;
            Desk.Service_Cliente.Crear_clienteResponse1 retVal = ((Desk.Service_Cliente.ClienteService)(this)).Crear_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Crear_clienteResponse1> Desk.Service_Cliente.ClienteService.Crear_clienteAsync(Desk.Service_Cliente.Crear_clienteRequest request) {
            return base.Channel.Crear_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Cliente.Crear_clienteResponse1> Crear_clienteAsync(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            Desk.Service_Cliente.Crear_clienteRequest inValue = new Desk.Service_Cliente.Crear_clienteRequest();
            inValue.id = id;
            inValue.fecha_nacimiento = fecha_nacimiento;
            inValue.correo = correo;
            inValue.password = password;
            inValue.telefono = telefono;
            inValue.acepta_informativo = acepta_informativo;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_actualizacion = fecha_actualizacion;
            inValue.id_ciudad = id_ciudad;
            inValue.id_estado = id_estado;
            inValue.id_persona = id_persona;
            return ((Desk.Service_Cliente.ClienteService)(this)).Crear_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Cliente.Listado_clientesResponse Desk.Service_Cliente.ClienteService.Listado_clientes(Desk.Service_Cliente.Listado_clientesRequest request) {
            return base.Channel.Listado_clientes(request);
        }
        
        public Desk.Service_Cliente.cliente[] Listado_clientes() {
            Desk.Service_Cliente.Listado_clientesRequest inValue = new Desk.Service_Cliente.Listado_clientesRequest();
            Desk.Service_Cliente.Listado_clientesResponse retVal = ((Desk.Service_Cliente.ClienteService)(this)).Listado_clientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Listado_clientesResponse> Desk.Service_Cliente.ClienteService.Listado_clientesAsync(Desk.Service_Cliente.Listado_clientesRequest request) {
            return base.Channel.Listado_clientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Cliente.Listado_clientesResponse> Listado_clientesAsync() {
            Desk.Service_Cliente.Listado_clientesRequest inValue = new Desk.Service_Cliente.Listado_clientesRequest();
            return ((Desk.Service_Cliente.ClienteService)(this)).Listado_clientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desk.Service_Cliente.Modificar_clienteResponse1 Desk.Service_Cliente.ClienteService.Modificar_cliente(Desk.Service_Cliente.Modificar_clienteRequest request) {
            return base.Channel.Modificar_cliente(request);
        }
        
        public string Modificar_cliente(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            Desk.Service_Cliente.Modificar_clienteRequest inValue = new Desk.Service_Cliente.Modificar_clienteRequest();
            inValue.id = id;
            inValue.fecha_nacimiento = fecha_nacimiento;
            inValue.correo = correo;
            inValue.password = password;
            inValue.telefono = telefono;
            inValue.acepta_informativo = acepta_informativo;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_actualizacion = fecha_actualizacion;
            inValue.id_ciudad = id_ciudad;
            inValue.id_estado = id_estado;
            inValue.id_persona = id_persona;
            Desk.Service_Cliente.Modificar_clienteResponse1 retVal = ((Desk.Service_Cliente.ClienteService)(this)).Modificar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desk.Service_Cliente.Modificar_clienteResponse1> Desk.Service_Cliente.ClienteService.Modificar_clienteAsync(Desk.Service_Cliente.Modificar_clienteRequest request) {
            return base.Channel.Modificar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desk.Service_Cliente.Modificar_clienteResponse1> Modificar_clienteAsync(int id, System.DateTime fecha_nacimiento, string correo, string password, int telefono, string acepta_informativo, System.DateTime fecha_inicio, System.DateTime fecha_actualizacion, int id_ciudad, int id_estado, int id_persona) {
            Desk.Service_Cliente.Modificar_clienteRequest inValue = new Desk.Service_Cliente.Modificar_clienteRequest();
            inValue.id = id;
            inValue.fecha_nacimiento = fecha_nacimiento;
            inValue.correo = correo;
            inValue.password = password;
            inValue.telefono = telefono;
            inValue.acepta_informativo = acepta_informativo;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_actualizacion = fecha_actualizacion;
            inValue.id_ciudad = id_ciudad;
            inValue.id_estado = id_estado;
            inValue.id_persona = id_persona;
            return ((Desk.Service_Cliente.ClienteService)(this)).Modificar_clienteAsync(inValue);
        }
    }
}
